---
- name: Parcha un conjunto de servidores linux
  hosts: all
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al hermoso mundo de ansible"

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      become: true
