---
- name: Parcha un conjunto de servidores linux
  hosts: all
  vars:
    cron_pkg_name: chrony
    var_system_crypto_policy: DEFAULT
    var_account_disable_post_pw_expiration: '30'
    var_accounts_maximum_age_login_defs: '100'
    var_with_faillock: with-faillock

  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Los Ganadores - Los Guandolos y las Reglas"

    - name: Regla 1. Install cron in Guandolos
      package:
        name: '{{ cron_pkg_name }}'
        state: present
      become: true
    
    - name: Regla 2. Configure System Cryptography Policy in Guandolos
      lineinfile:
        path: /etc/crypto-policies/config
        regexp: ^(?!#)(\S+)$
        line: '{{ var_system_crypto_policy }}'
        create: true
      become: true  

    - name: Verify that Crypto Policy is Set (runtime) in Guandolos
      command: /usr/bin/update-crypto-policies --set {{ var_system_crypto_policy }}
      become: true

    - name: Regla 3. Ensure gdm is removed
      package:
        name: gdm
        state: absent
      become: true

    - name: Regla 4. Set Account Expiration Following Inactivity
      lineinfile:
        create: true
        dest: /etc/default/useradd
        regexp: ^INACTIVE
        line: INACTIVE={{ var_account_disable_post_pw_expiration }}
      become: true
    
    - name: Regla 5. Set Password Maximum Age
      lineinfile:
        create: true
        dest: /etc/login.defs
        regexp: ^#?PASS_MAX_DAYS
        line: PASS_MAX_DAYS {{ var_accounts_maximum_age_login_defs }}
      become: true
    
    - name: Regla 6. Collect users with not correct maximum time period between password changes in Guandolos
      ansible.builtin.command:
        cmd: awk -F':' '(/^[^:]+:[^!*]/ && ($5 > {{ var_accounts_maximum_age_login_defs }} || $5 == "")) {print $1}' /etc/shadow
      register: user_names
      become: true

    - name: Regla 7. Enable service firewalld in Guandolos
      block:
      - name: Gather the package facts
        package_facts:
          manager: auto
      - name: Enable service firewalld
        systemd:
          name: firewalld
          enabled: 'no'
          state: stopped
          masked: 'yes'
      become: true

    - name: Regla 8. Ensure sudo is installed in Guandolos
      package:
        name: sudo
        state: present
      become: true

    - name: Regla 9. Install with-faillock in Guandolos
      package:
        name: '{{ var_with_faillock }}'
        state: present
      become: true