---
- name: Parcha un conjunto de servidores linux
  hosts: all
  vars:
    cron_pkg_name: chrony
    var_system_crypto_policy: DEFAULT

  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Los Ganadores - Los Guandolos y las Reglas"

    - name: Regla 1. Install cron in Guandolos
      package:
        name: '{{ cron_pkg_name }}'
        state: present
    
    - name: Regla 2. Configure System Cryptography Policy in Guandolos
      lineinfile:
        path: /etc/crypto-policies/config
        regexp: ^(?!#)(\S+)$
        line: '{{ var_system_crypto_policy }}'
        create: true

    - name: Verify that Crypto Policy is Set (runtime) in Guandolos
      command: /usr/bin/update-crypto-policies --set {{ var_system_crypto_policy }}

    - name: Regla 3. Ensure gdm is removed
      package:
        name: gdm
        state: absent